parserOptions:
  ecmaVersion: latest
  sourceType: 'module'

env:
  es2017: true
  browser: true

extends: [
  'htmlacademy/vanilla',
  'plugin:@typescript-eslint/eslint-recommended',
  'plugin:@typescript-eslint/recommended'
]
